# Generated by Django 1.11.29 on 2020-04-14 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="An image to represent this group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.IETFImage",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="This group's role within the IETF.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="snippets.Role",
            ),
        ),
        migrations.AlterField(
            model_name="rfc",
            name="working_group",
            field=models.ForeignKey(
                blank=True,
                help_text="The working group that produced this RFC",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="snippets.WorkingGroup",
            ),
        ),
    ]
