# Generated by Django 4.2.7 on 2023-12-11 09:19

from django.db import migrations, models


def https_links(apps, schema_editor):
    WorkingGroup = apps.get_model("snippets.WorkingGroup")
    for wg in WorkingGroup.objects.all():
        if wg.list_subscribe.startswith("http://www.ietf.org"):
            wg.list_subscribe = wg.list_subscribe.replace("http://", "https://")
            wg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20200414_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinggroup',
            name='list_subscribe',
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(https_links, migrations.RunPython.noop),
    ]
