# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0026_auto_20170227_1401'),
    ]

    operations = [
    ]
