# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0027_move_news_to_secondary'),
        ('utils', '0011_remove_snippits_primarytopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarytopic',
            name='page',
        ),
        migrations.DeleteModel(
            name='PrimaryTopic',
        ),
    ]
