# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-10 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0031_slug_unique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecondaryTopic',
            new_name='Topic',
        ),
    ]
