# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-03 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0032_rename_secondarytopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='page',
        ),
    ]
