# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-03 20:51
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    ''' Takes the author names in use by BlogPageAuthor and puts them in ietf.snippets.Person.
        This relies on the current truth that we have no names in use by BlogPageAuthor that
        point to more than one real person.
    '''
    BlogPageAuthor = apps.get_model('blog','BlogPageAuthor')
    Person = apps.get_model('snippets','Person')
    for person_name in BlogPageAuthor.objects.values_list('author__name',flat=True).distinct():
        Person.objects.create(name=person_name)

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0034_person'),
        ('blog', '0029_rename_blogpagetopic_secondarytopics')
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
