# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0035_populate_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511, unique=True)),
                ('title', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Charter',
                'ordering': ['title'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='RFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('title', models.TextField(blank=True)),
                ('rfc', models.CharField(help_text="The RFC's number (without any letters)", max_length=511, unique=True)),
                ('abstract', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'RFC',
                'ordering': ['title'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='WorkingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('acronym', models.CharField(blank=True, max_length=511)),
                ('description', models.CharField(blank=True, max_length=4096)),
                ('list_email', models.EmailField(blank=True, max_length=254)),
                ('list_subscribe', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Working Group',
                'ordering': ['name'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.AddField(
            model_name='rfc',
            name='working_group',
            field=models.ForeignKey(blank=True, help_text='The working group that produced this RFC', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snippets.WorkingGroup'),
        ),
        migrations.AddField(
            model_name='charter',
            name='working_group',
            field=models.ForeignKey(blank=True, help_text="This charter's working group", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snippets.WorkingGroup'),
        ),
    ]
