# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-06 23:21
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    MailingListSignup = apps.get_model('snippets', 'MailingListSignup')
    WorkingGroup = apps.get_model('snippets','WorkingGroup')
    for mls in MailingListSignup.objects.filter(working_group__isnull=False):
        mls.snippets_working_group = WorkingGroup.objects.get(acronym=mls.working_group.acronym)
        mls.save()

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0038_mailinglistsignup_snippets_working_group'),
    ]

    operations = [
        migrations.RunPython(forward,reverse)
    ]
