# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-06 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0039_populate_mailinglistsignup_snippets_working_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglistsignup',
            name='working_group',
        ),
    ]
