# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-07 20:32
from __future__ import unicode_literals

from django.db import migrations, connection, transaction

from wagtail.documents.models import Document

def forward(apps, schema_editor):
    IetfDocument = apps.get_model('documents', 'IetfDocument')

    # See https://stackoverflow.com/questions/4298278/django-using-custom-raw-sql-inserts-with-executemany-and-mysql
    cursor = connection.cursor()
    query = ' INSERT INTO documents_ietfdocument (document_ptr_id) values (%s) '
    queryList = Document.objects.values_list('pk')
    cursor.executemany(query,queryList)
#    transaction.commit()

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward,reverse)
    ]
