# Generated by Django 2.2.12 on 2020-04-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ietfdocument",
            options={"verbose_name": "document", "verbose_name_plural": "documents"},
        ),
    ]
