# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0023_auto_20171023_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarytopicpage',
            name='introduction',
            field=models.CharField(blank=True, help_text='Enter the title to display on the page, you can use only 255 characters.', max_length=255),
        ),
        migrations.AlterField(
            model_name='secondarytopicpage',
            name='introduction',
            field=models.CharField(blank=True, help_text='Enter the introduction to display on the page, you can use only 255 characters.', max_length=255),
        ),
    ]
