[tool.pytest.ini_options]
addopts = "--reuse-db"
python_files = "ietf/*/test*.py"
filterwarnings = [
    "error",
    "ignore::django.utils.deprecation.RemovedInDjango60Warning",
    "ignore::UserWarning",
]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
extend-select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
]

extend-ignore = [
    "E501",  # no line length errors
]
