# Generated by Django 3.2.13 on 2023-02-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0005_iabstandardpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iabstandardpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='iabstandardpage',
            name='in_depth',
        ),
        migrations.RemoveField(
            model_name='iabstandardpage',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='iabstandardpage',
            name='key_info',
        ),
        migrations.RemoveField(
            model_name='iabstandardpage',
            name='mailing_list_signup',
        ),
        migrations.RemoveField(
            model_name='iabstandardpage',
            name='prepared_in_depth',
        ),
        migrations.RemoveField(
            model_name='iabstandardpage',
            name='prepared_key_info',
        ),
    ]
