# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0020_auto_20180116_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardindexpage',
            name='introduction',
            field=models.CharField(help_text='Enter the title to display on the page, you can use only 255 characters yes.', max_length=255),
        ),
    ]
