# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0021_auto_20180201_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardindexpage',
            name='introduction',
            field=models.CharField(blank=True, help_text='Enter the title to display on the page, you can use only 255 characters.', max_length=255),
        ),
    ]
