# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-07 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0022_auto_20180201_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpagearea',
            name='area',
        ),
        migrations.RemoveField(
            model_name='standardpagearea',
            name='page',
        ),
        migrations.RemoveField(
            model_name='standardpagecharter',
            name='charter',
        ),
        migrations.RemoveField(
            model_name='standardpagecharter',
            name='page',
        ),
        migrations.RemoveField(
            model_name='standardpageinternetdraft',
            name='internet_draft',
        ),
        migrations.RemoveField(
            model_name='standardpageinternetdraft',
            name='page',
        ),
        migrations.RemoveField(
            model_name='standardpagerfc',
            name='page',
        ),
        migrations.RemoveField(
            model_name='standardpagerfc',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='standardpageworkinggroup',
            name='page',
        ),
        migrations.RemoveField(
            model_name='standardpageworkinggroup',
            name='working_group',
        ),
        migrations.DeleteModel(
            name='StandardPageArea',
        ),
        migrations.DeleteModel(
            name='StandardPageCharter',
        ),
        migrations.DeleteModel(
            name='StandardPageInternetDraft',
        ),
        migrations.DeleteModel(
            name='StandardPageRFC',
        ),
        migrations.DeleteModel(
            name='StandardPageWorkingGroup',
        ),
    ]
