# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatracker', '0025_auto_20180123_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charter',
            name='name',
            field=models.CharField(max_length=511, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='resource_uri',
            field=models.CharField(max_length=511, unique=True),
        ),
        migrations.AlterField(
            model_name='internetdraft',
            name='name',
            field=models.CharField(max_length=511, unique=True),
        ),
        migrations.AlterField(
            model_name='rfc',
            name='rfc',
            field=models.CharField(max_length=511, unique=True),
        ),
        migrations.AlterField(
            model_name='rolename',
            name='slug',
            field=models.CharField(max_length=511, unique=True),
        ),
    ]
