namespace: ietfwww
namePrefix: ietfwww-
configMapGenerator:
  - name: files-cfgmap
    files:
      - local.py
      - supervisord.conf
      - nginx-default.conf
      - nginx.conf
resources:
  - memcached.yaml
  - wagtail.yaml
