namespace: ietfwww
labels:
  - pairs:
      app.kubernetes.io/part-of: ietfwww
      io.portainer.kubernetes.application.stack: ietfwww
    includeTemplates: true
configMapGenerator:
  - name: ietfwww-files-cfgmap
    files:
      - local.py
      - supervisord.conf
      - nginx-default.conf
      - nginx.conf
resources:
  - memcached.yaml
  - wagtail.yaml
  - cron.yaml
