apiVersion: v1
kind: Secret
metadata:
  name: secrets-env
type: Opaque
stringData:
  IETFWWW_ADMINS: null

  IETFWWW_ALLOWED_HOSTS: ".ietf.org"  # newline-separated list also allowed
  WAGTAILADMIN_BASE_URL: "https://www.ietf.org"

  # Outgoing email details
  IETFWWW_EMAIL_HOST: null
  IETFWWW_EMAIL_PORT: null

  IETFWWW_MATOMO_SITE_ID: null  # must be present to enable Matomo

  # Can also be a newline-separated list
  IETFWWW_CSRF_TRUSTED_ORIGINS: "https://www.ietf.org"

  # Database connection details - to be fetched from Vault
  # IETFWWW_DB_HOST: ""
  # IETFWWW_DB_NAME: ""
  # IETFWWW_DB_PASS: ""
  # IETFWWW_DB_PORT: ""
  # IETFWWW_DB_USER: ""

  # Django secret key - to be fetched from Vault
  # IETFWWW_DJANGO_SECRET_KEY: ""
