apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ietfwww-wagtail
  labels:
    app.kubernetes.io/name: wagtail
    app.kubernetes.io/instance: ietfwww-wagtail
    app.kubernetes.io/version: "$APP_IMAGE_TAG"
    app.kubernetes.io/component: website
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: ietfwww-wagtail
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wagtail
        app.kubernetes.io/instance: ietfwww-wagtail
        app.kubernetes.io/version: "$APP_IMAGE_TAG"
        app.kubernetes.io/component: website
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
      containers:
        # -----------------------------------------------------
        # wagtail Container
        # -----------------------------------------------------
        - name: ietfwww-wagtail
          image: "ghcr.io/ietf-tools/www:$APP_IMAGE_TAG"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: dt-vol
              mountPath: /a
            - name: www-tmp
              mountPath: /tmp
            - name: www-nginx
              mountPath: /var/lib/nginx
            - name: www-media
              mountPath: /app/media
            - name: www-cfg
              mountPath: /app/supervisord.conf
              subPath: supervisord.conf
            - name: www-cfg
              mountPath: /app/ietf/settings/local.py
              subPath: local.py
            - name: www-cfg
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: www-cfg
              mountPath: /etc/nginx/sites-enabled/default
              subPath: nginx-default.conf
          env:
            - name: "CONTAINER_ROLE"
              value: "ietfweb"
            - name: "DJANGO_SETTINGS_MODULE"
              value: "ietf.settings.production"
            # ensures the pod gets recreated on every deploy:
            - name: "DEPLOY_UID"
              value: "$DEPLOY_UID"
          envFrom:
            - secretRef:
                name: ietfwww-secrets-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        # To be overriden with the actual shared volume
        - name: dt-vol
        # ---
        - name: www-tmp
          emptyDir:
            sizeLimit: "1Gi"
        - name: www-nginx
          emptyDir:
            sizeLimit: "1Gi"
        - name: www-cfg
          configMap:
            name: ietfwww-files-cfgmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      # ensures we don't schedule this pod on the same node as iabwww:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - iabwww-wagtail
            topologyKey: "kubernetes.io/hostname"
            namespaceSelector: {}
  volumeClaimTemplates:
  - metadata:
      name: www-media
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: "generic"
---
apiVersion: v1
kind: Service
metadata:
  name: ietfwww-wagtail
  labels:
    app.kubernetes.io/name: wagtail
    app.kubernetes.io/instance: ietfwww-wagtail
    app.kubernetes.io/version: "$APP_IMAGE_TAG"
    app.kubernetes.io/component: website
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: ietfwww-wagtail
