apiVersion: v1
kind: Secret
metadata:
  name: secrets-env
type: Opaque
stringData:
  IABWWW_ADMINS: null

  IABWWW_ALLOWED_HOSTS: ".iab.org"  # newline-separated list also allowed
  WAGTAILADMIN_BASE_URL: "https://www.iab.org"

  # Outgoing email details
  IABWWW_EMAIL_HOST: null
  IABWWW_EMAIL_PORT: null

  IABWWW_MATOMO_SITE_ID: null  # must be present to enable Matomo

  # Can also be a newline-separated list
  IABWWW_CSRF_TRUSTED_ORIGINS: "https://www.iab.org"

  # Database connection details - to be fetched from Vault
  # IABWWW_DB_HOST: ""
  # IABWWW_DB_NAME: ""
  # IABWWW_DB_PASS: ""
  # IABWWW_DB_PORT: ""
  # IABWWW_DB_USER: ""

  # Django secret key - to be fetched from Vault
  # IABWWW_DJANGO_SECRET_KEY: ""
