apiVersion: v1
kind: Secret
metadata:
  name: secrets-env
type: Opaque
stringData:
  # Database connection details - to be overridden
  IABWWW_DB_HOST: "host"
  IABWWW_DB_NAME: "name"
  IABWWW_DB_PASS: "pass"
  IABWWW_DB_PORT: "port"
  IABWWW_DB_USER: "user"

  # Django secret key - to be overridden
  IABWWW_DJANGO_SECRET_KEY: "secret"
