# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20171023_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='key_details_expanded',
            field=models.BooleanField(default=False, help_text='Show the key details items expanded when the page first loads'),
        ),
    ]
