# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_eventpage_key_details_expanded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlistingpage',
            name='introduction',
            field=models.CharField(blank=True, max_length=511),
        ),
    ]
