# Generated by Django 3.2.13 on 2023-02-19 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("images", "0002_alter_ietfimage_file_hash"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IABHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("button_text", models.CharField(blank=True, max_length=255)),
                (
                    "button_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "main_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.ietfimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "IAB Home Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
