# Generated by Django 3.2.13 on 2023-02-01 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IABHomePage",
            fields=[
                (
                    "homepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.homepage",),
        ),
    ]
