# Generated by Django 3.2.13 on 2023-02-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_iabhomepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iabhomepage",
            options={"verbose_name": "IAB Home Page"},
        ),
    ]
