# Generated by Django 4.2.7 on 2023-12-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_iabhomepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinggroupssectionlinks',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='workinggroupssectionlinks',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='workinggroupssectionlinks',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlighted_request_for_comment',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlighted_working_group',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='request_for_comments_section_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='working_groups_section_body',
        ),
        migrations.DeleteModel(
            name='RequestForCommentsSectionLinks',
        ),
        migrations.DeleteModel(
            name='WorkingGroupsSectionLinks',
        ),
    ]
