# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-06 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0038_mailinglistsignup_snippets_working_group'),
        ('home', '0006_auto_20160315_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='snippets_highlighted_working_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.WorkingGroup'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='snippets_highlighted_request_for_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.RFC'),
        ),
    ]
