# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-06 23:22
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    HomePage = apps.get_model('home', 'HomePage')
    WorkingGroup = apps.get_model('snippets', 'WorkingGroup')
    RFC = apps.get_model('snippets', 'RFC')

    hp = HomePage.objects.last()
    hp.snippets_highlighted_working_group = WorkingGroup.objects.get(acronym=hp.highlighted_working_group.acronym)
    hp.snippets_highlighted_request_for_comment = RFC.objects.get(rfc=hp.highlighted_request_for_comment.rfc)
    hp.save()

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_snippets_wg_and_rfc'),
        ('snippets', '0037_populate_snippets_from_dt'),
    ]

    operations = [
        migrations.RunPython(forward,reverse)
    ]
