# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-06 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_populate_homepage_snippets_wg_and_rfc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='highlighted_request_for_comment',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlighted_working_group',
        ),
    ]
