# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-06 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_highlighted_wg_and_rfc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='snippets_highlighted_request_for_comment',
            new_name='highlighted_request_for_comment',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='snippets_highlighted_working_group',
            new_name='highlighted_working_group',
        ),
    ]
