# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-07 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_snippets_highlighted_wg_and_rfc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetdraftssectionlinks',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='internetdraftssectionlinks',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='internetdraftssectionlinks',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='highlighted_internet_draft',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='internet_drafts_section_body',
        ),
        migrations.DeleteModel(
            name='InternetDraftsSectionLinks',
        ),
    ]
