# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


# Migrations 0020, 0021, 0022 and 0023 are fixing old constraints as
# described in
# https://projects.torchbox.com/projects/ietf/tickets/161#update-46365457


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_remove_ietfrendition_filter'),
        ('blog', '0019_auto_20170707_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='feed_image_2',
            field=models.ForeignKey(blank=True, help_text='This image will be used in listings and indexes across the site, if no feed image is added, the social image will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.IETFImage'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_image_2',
            field=models.ForeignKey(blank=True, help_text="Image to appear alongside 'social text', particularly for sharing on social networks", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.IETFImage'),
        ),
    ]
