# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 13:37
from __future__ import unicode_literals

from django.db import migrations


# Migrations 0020, 0021, 0022 and 0023 are fixing old constraints as
# described in
# https://projects.torchbox.com/projects/ietf/tickets/161#update-46365457

# Note on migrationg page revisions
#   Don't think we have to migrate page revisions since we
#   bring back the old field names later on.


def move_blog_images(apps, schema, from_field, to_field):
    BlogPage = apps.get_model('blog.BlogPage')
    # Could use update on the whole queryset, but feel like save()
    # is just safer.
    queryset = BlogPage.objects.select_related(from_field, to_field)
    for blog in queryset:
        changed = False
        if getattr(blog, from_field):
            setattr(blog, to_field, getattr(blog, from_field))
            setattr(blog, from_field, None)
            changed = True
        if not changed:
            continue
        blog.save()


def migrate_blog_social_and_feed_images(apps, schema):
    move_blog_images(apps, schema, 'social_image', 'social_image_2')
    move_blog_images(apps, schema, 'feed_image', 'feed_image_2')


def reverse_migrate_blog_social_and_feed_images(apps, schema):
    move_blog_images(apps, schema, 'social_image_2', 'social_image')
    move_blog_images(apps, schema, 'feed_image_2', 'feed_image')


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blog_page_add_new_social_and_field_image_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_blog_social_and_feed_images,
                             reverse_migrate_blog_social_and_feed_images)
    ]
