# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 13:40
from __future__ import unicode_literals

from django.db import migrations


# Migrations 0020, 0021, 0022 and 0023 are fixing old constraints as
# described in
# https://projects.torchbox.com/projects/ietf/tickets/161#update-46365457


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blog_migrate_social_and_field_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_image',
        ),
    ]
