# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 13:40
from __future__ import unicode_literals

from django.db import migrations


# Migrations 0020, 0021, 0022 and 0023 are fixing old constraints as
# described in
# https://projects.torchbox.com/projects/ietf/tickets/161#update-46365457


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blogpage_remove_old_social_and_feed_image_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='feed_image_2',
            new_name='feed_image',
        ),
        migrations.RenameField(
            model_name='blogpage',
            old_name='social_image_2',
            new_name='social_image',
        ),
    ]
