# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171023_1025'),
        ('blog', '0023_blogpage_rename_temporary_social_and_feed_images_to_the_proper_field_names'),
    ]

    operations = [
    ]
