# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171023_1025'),
        ('blog', '0024_table_block'),
    ]

    operations = [
    ]
