# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_merge_20171114_0952'),
        ('blog', '0025_merge_20171207_1706'),
    ]

    operations = [
    ]
