# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_merge_20171219_1320'),
        ('snippets','0027_move_news_to_secondary'),

    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpageprimarytopic',
            name='page',
        ),
        migrations.RemoveField(
            model_name='blogpageprimarytopic',
            name='topic',
        ),
        migrations.DeleteModel(
            name='BlogPagePrimaryTopic',
        ),
    ]
