# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-14 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_snippits_primarytopic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPageSecondaryTopic',
            new_name='BlogPageTopic',
        ),
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Blog Index Page'},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog Page'},
        ),
    ]
