# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-14 22:28
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_rename_blogpagesecondarytopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagetopic',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='blog.BlogPage'),
        ),
    ]
