# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-03 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0035_populate_person'),
        ('blog', '0029_rename_blogpagetopic_secondarytopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpageauthor',
            name='author_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='snippets.Person'),
        ),
    ]
