# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-03 21:33
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    BlogPageAuthor = apps.get_model('blog','BlogPageAuthor')
    Person = apps.get_model('snippets','Person')
    for bpa in BlogPageAuthor.objects.all():
        bpa.author_snippet = Person.objects.get(name=bpa.author.name)

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_blogpageauthor_author_snippet'),
        ('snippets', '0035_populate_person')
    ]

    operations = [
    ]
