# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-04 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_populate_author_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpageauthor',
            name='author',
        ),
    ]
