# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-04 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_blogpageauthor_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpageauthor',
            old_name='author_snippet',
            new_name='author',
        ),
    ]
