# Generated by Django 4.2.7 on 2023-11-29 12:17

import wagtail.images.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_wagtail_42_wagtailimagefield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ietfrendition",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
    ]
