# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_remove_ietfrendition_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ietfimage',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
    ]
