# Generated by Django 2.2.19 on 2021-11-03 21:45

from django.db import migrations


menu_items = [
    {
        "fields": {
            "sort_order": 1,
            "page": 34,
            "text": ""
        },
        "sub_menu": [
            {
                "sort_order": 0,
                "parent": 1,
                "page": 33,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 1,
                "parent": 1,
                "page": 58,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 2,
                "parent": 1,
                "page": 1668,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 3,
                "parent": 1,
                "page": 357,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 4,
                "parent": 1,
                "page": 1181,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 5,
                "parent": 1,
                "page": 2010,
                "link": "",
                "text": ""
            },
        ]
    },
    {
        "fields": {
            "sort_order": 2,
            "page": 36,
            "text": ""
        },
        "sub_menu": [
            {
                "sort_order": 0,
                "parent": 2,
                "page": 1301,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 1,
                "parent": 2,
                "page": 39,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 2,
                "parent": 2,
                "page": 1302,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 3,
                "parent": 2,
                "page": 1790,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 4,
                "parent": 2,
                "page": 1441,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 5,
                "parent": 2,
                "page": 1886,
                "link": "",
                "text": ""
            }
        ]
    },
    {
        "fields": {
            "sort_order": 3,
            "page": 45,
            "text": ""
        },
        "sub_menu": [
            {
                "sort_order": 0,
                "parent": 3,
                "page": 51,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 1,
                "parent": 3,
                "page": 256,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 2,
                "parent": 3,
                "page": 30,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 3,
                "parent": 3,
                "page": 280,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 4,
                "parent": 3,
                "page": 1051,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 5,
                "parent": 3,
                "page": 1106,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 6,
                "parent": 3,
                "page": 2035,
                "link": "",
                "text": ""
            }
        ]
    },
    {
        "fields": {
            "sort_order": 4,
            "page": 47,
            "text": ""
        },
        "sub_menu": [
            {
                "sort_order": 0,
                "parent": 4,
                "page": 339,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 1,
                "parent": 4,
                "page": 340,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 2,
                "parent": 4,
                "page": 1053,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 3,
                "parent": 4,
                "page": 1391,
                "link": "",
                "text": ""
            },
            {
                "sort_order": 4,
                "parent": 4,
                "page": 2109,
                "link": "",
                "text": ""
            }
        ]
    },
    {
        "fields": {
            "sort_order": 5,
            "page": 42,
            "text": "News & blog"
        },
        "sub_menu": None
    },
]

def load_menu_data(apps, schema_editor):
    MenuItem = apps.get_model('utils', 'MenuItem')
    SubMenuItem = apps.get_model('utils', 'SubMenuItem')
    Page = apps.get_model('wagtailcore', 'Page')

    # Update existing
    contact_menu = MenuItem.objects.filter(page__title="Contact").first()
    if contact_menu is not None:
        contact_menu.sort_order = 6
        contact_menu.save()
    tools_menu = MenuItem.objects.filter(page__title="Links").first()
    if tools_menu is not None:
        tools_menu.text = "Tools"
        tools_menu.sort_order = 7
        tools_menu.save()

    # Add menu items that were previously hard coded
    for item in menu_items:
        page = Page.objects.filter(pk=item['fields']['page']).first()
        if page:
            menu_item = MenuItem(text=item['fields']['text'], page=page, sort_order=item['fields']['sort_order'])
            menu_item.save()
            sub_menu_items = item.get('sub_menu')
            if sub_menu_items is not None:
                for s in sub_menu_items:
                    sub_menu = SubMenuItem(parent=menu_item, text=s['text'], sort_order=s['sort_order'])
                    if s['page']:
                        page = Page.objects.filter(pk=s['page']).first()
                        if page:
                            sub_menu.page = page
                    else:
                        sub_menu.link = s['link']
                    sub_menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20211101_0113'),
    ]

    operations = [
        migrations.RunPython(load_menu_data),
    ]
