# Generated by Django 3.2.10 on 2022-01-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20211105_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name_plural': 'Secondary Menu'},
        ),
    ]
