# Generated by Django 3.2.13 on 2023-02-09 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("utils", "0004_alter_menuitem_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayoutSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_template",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("base.html", "IETF (default)"),
                            ("iab_base.html", "IAB"),
                        ],
                        default="base.html",
                        max_length=255,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
