# Generated by Django 3.2.13 on 2023-04-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_layoutsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextChunk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("text", models.TextField()),
            ],
        ),
    ]
