# Generated by Django 3.2.13 on 2023-05-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_auto_20230524_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='default_sharing_image',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='default_sharing_text',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='facebook_app_id',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='twitter_handle',
        ),
    ]
