# Generated by Django 3.2.13 on 2023-05-24 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_ietfimage_file_hash'),
        ('utils', '0007_auto_20230524_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='default_sharing_image',
            field=models.ForeignKey(blank=True, help_text='Default sharing image to use if social image has not been set on a page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.ietfimage'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='default_sharing_text',
            field=models.CharField(blank='True', help_text='Default sharing text to use if social text has not been set on a page.', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='facebook_app_id',
            field=models.CharField(blank='True', help_text='Your Facebook app id', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='site_name',
            field=models.CharField(blank='True', default='ietf', help_text='Site name, used by facebook open graph.', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter_handle',
            field=models.CharField(blank='True', help_text='Your Twitter username without the @, e.g. flickr', max_length=255),
        ),
    ]
