# Generated by Django 4.2.7 on 2023-12-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_auto_20230524_0551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='SecondaryMenuItem',
        ),
    ]
