# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('utils', '0008_auto_20170601_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_feed_title', models.CharField(blank=True, max_length=255)),
                ('blog_feed_description', models.CharField(blank=True, max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
