# Generated by Django 5.2.11 on 2026-02-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0010_footercolumn"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediasettings",
            name="bluesky",
            field=models.CharField(
                blank="True",
                help_text="Link to Bluesky profile",
                max_length=255,
                verbose_name="bluesky link",
            ),
        ),
    ]
