# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20181102_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandblogsmenuitem',
            name='model',
        ),
        migrations.RemoveField(
            model_name='newsandblogsmenuitem',
            name='snippet',
        ),
        migrations.DeleteModel(
            name='NewsAndBlogsMenuItem',
        ),
    ]
