# Generated by Django 5.2.11 on 2026-02-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0011_socialmediasettings_bluesky"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediasettings",
            name="facebook",
            field=models.CharField(
                blank="True",
                help_text="Link to Facebook profile",
                max_length=255,
                verbose_name="facebook link",
            ),
        ),
    ]
