# Generated by Django 5.2.11 on 2026-02-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0012_socialmediasettings_facebook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmediasettings",
            name="facebook_app_id",
        ),
    ]
