# Generated by Django 5.2.11 on 2026-02-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0013_remove_socialmediasettings_facebook_app_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmediasettings",
            name="twitter_handle",
        ),
    ]
